
// This file has been generated by the GUI designer. Do not modify.
namespace Minesweeper.Views
{
	public partial class GameWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action GameAction;
		
		private global::Gtk.Action RetryAction;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.DrawingArea daInfoBar;
		
		private global::Gtk.DrawingArea daTable;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Minesweeper.Views.GameWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.GameAction = new global::Gtk.Action ("GameAction", global::Mono.Unix.Catalog.GetString ("Game"), null, null);
			this.GameAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game");
			w1.Add (this.GameAction, null);
			this.RetryAction = new global::Gtk.Action ("RetryAction", global::Mono.Unix.Catalog.GetString ("Retry"), null, null);
			this.RetryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Retry");
			w1.Add (this.RetryAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Minesweeper.Views.GameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Minesweeper");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Minesweeper.Resources.minesweeper.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child Minesweeper.Views.GameWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='GameAction' action='GameAction'><menuitem name='RetryAction' action='RetryAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox2.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.daInfoBar = new global::Gtk.DrawingArea ();
			this.daInfoBar.HeightRequest = 64;
			this.daInfoBar.Name = "daInfoBar";
			this.vbox2.Add (this.daInfoBar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.daInfoBar]));
			w3.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.daTable = new global::Gtk.DrawingArea ();
			this.daTable.WidthRequest = 480;
			this.daTable.HeightRequest = 480;
			this.daTable.Name = "daTable";
			this.vbox2.Add (this.daTable);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.daTable]));
			w4.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 480;
			this.DefaultHeight = 569;
			this.Show ();
			this.RetryAction.Activated += new global::System.EventHandler (this.OnRetryActionActivated);
			this.daTable.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDaTableButtonPressEvent);
		}
	}
}
